#!/usr/bin/env python3
"""
Create PowerShell module scaffold with manifest and script file.
"""
import argparse
import os
import uuid
from pathlib import Path

def create_manifest(module_dir: str, module_name: str, functions: list) -> str:
    """Generate PowerShell module manifest (.psd1)."""
    guid = str(uuid.uuid4())
    functions_list = ', '.join([f"'{f}'" for f in functions])
    aliases = [f"'{f.lower().replace('-', '-')}'" for f in functions]
    aliases_list = ', '.join(aliases) if aliases else "@()"
    
    content = f'''@{{
    RootModule = '{module_name}.psm1'
    ModuleVersion = '1.0.0'
    GUID = '{guid}'
    Author = '{module_name}'
    CompanyName = '{module_name}'
    Copyright = '(c) 2026 {module_name}. All rights reserved.'
    Description = 'PowerShell module generated by powershell-module-builder skill'
    PowerShellVersion = '5.1'
    FunctionsToExport = @({functions_list})
    CmdletsToExport = @()
    VariablesToExport = @()
    AliasesToExport = @({aliases_list})
    PrivateData = @{{
        PSData = @{{
            Tags = @('automation', 'windows')
            ReleaseNotes = 'Initial release'
        }}
    }}
}}'''
    path = os.path.join(module_dir, f"{module_name}.psd1")
    with open(path, 'w') as f:
        f.write(content)
    return path

def create_script(module_dir: str, module_name: str, functions: list) -> str:
    """Generate PowerShell script module (.psm1) with function stubs."""
    content = f'''# {module_name} PowerShell Module
# Generated by powershell-module-builder skill

'''
    
    for func in functions:
        content += f'''
function {func} {{
    <#
    .SYNOPSIS
        {func} function
    #>
    [CmdletBinding()]
    param()
    
    Write-Host "{func} executed"
}}
'''
    
    # Add aliases
    content += '\n# Aliases\n'
    for func in functions:
        alias = func.lower().replace('-', '-')
        content += f"Set-Alias -Name {alias} -Value {func}\n"
    
    # Export
    functions_export = ', '.join(functions)
    content += f"\nExport-ModuleMember -Function {functions_export}\n"
    
    path = os.path.join(module_dir, f"{module_name}.psm1")
    with open(path, 'w') as f:
        f.write(content)
    return path

def main():
    parser = argparse.ArgumentParser(description='Create PowerShell module')
    parser.add_argument('--name', required=True, help='Module name')
    parser.add_argument('--output', required=True, help='Output directory')
    parser.add_argument('--functions', default='Get-Status', help='Comma-separated function names')
    args = parser.parse_args()
    
    module_dir = os.path.join(args.output, args.name)
    os.makedirs(module_dir, exist_ok=True)
    
    functions = [f.strip() for f in args.functions.split(',')]
    
    print(f"Creating PowerShell module: {args.name}")
    
    create_manifest(module_dir, args.name, functions)
    create_script(module_dir, args.name, functions)
    
    print(f"✓ Module created at: {module_dir}")
    print(f"  - {args.name}.psd1 (manifest)")
    print(f"  - {args.name}.psm1 (script module)")
    print(f"\nFunctions: {', '.join(functions)}")

if __name__ == '__main__':
    main()