#!/usr/bin/env python3
"""
Generate mouse simulation code for C# or PowerShell.
"""
import argparse
import os

CSHARP_TEMPLATE = '''using System;
using System.Runtime.InteropServices;
using System.Threading;

namespace MouseInput
{{
    public static class MouseSimulator
    {{
        [DllImport("user32.dll")]
        static extern bool SetCursorPos(int x, int y);
        
        [DllImport("user32.dll")]
        static extern bool GetCursorPos(out POINT lpPoint);
        
        [DllImport("user32.dll")]
        static extern void mouse_event(uint dwFlags, uint dx, uint dy, uint dwData, int dwExtraInfo);
        
        [StructLayout(LayoutKind.Sequential)]
        public struct POINT
        {{
            public int X;
            public int Y;
        }}
        
        const uint MOUSEEVENTF_MOVE = 0x0001;
        
        private static Thread? jiggleThread;
        private static bool isRunning = false;
        private static bool zenMode = false;
        private static int intervalMs = 1000;
        
        public static event EventHandler? StatusChanged;
        
        public static void Start(bool virtualMode = false, int interval = 1000)
        {{
            if (isRunning) return;
            
            zenMode = virtualMode;
            intervalMs = interval;
            isRunning = true;
            
            jiggleThread = new Thread(JiggleLoop);
            jiggleThread.IsBackground = true;
            jiggleThread.Start();
            
            StatusChanged?.Invoke(null, EventArgs.Empty);
        }}
        
        public static void Stop()
        {{
            isRunning = false;
            jiggleThread?.Join(100);
            StatusChanged?.Invoke(null, EventArgs.Empty);
        }}
        
        public static bool IsRunning => isRunning;
        public static bool IsZenMode => zenMode;
        public static int Interval => intervalMs;
        
        private static void JiggleLoop()
        {{
            while (isRunning)
            {{
                try
                {{
                    if (zenMode)
                    {{
                        // Virtual mode: simulate input without moving cursor
                        mouse_event(MOUSEEVENTF_MOVE, 1, 0, 0, 0);
                        Thread.Sleep(10);
                        mouse_event(MOUSEEVENTF_MOVE, 0xFFFFFFFF, 0, 0, 0);
                    }}
                    else
                    {{
                        // Physical mode: move cursor slightly
                        GetCursorPos(out POINT point);
                        SetCursorPos(point.X + 1, point.Y);
                        Thread.Sleep(10);
                        SetCursorPos(point.X, point.Y);
                    }}
                }}
                catch {{ }}
                
                Thread.Sleep(intervalMs);
            }}
        }}
    }}
}}'''

POWERSHELL_TEMPLATE = '''# Mouse Simulator PowerShell Module
# Generated by mouse-input-simulator skill

Add-Type -TypeDefinition @"
using System;
using System.Runtime.InteropServices;
using System.Threading;

public class MouseSimulatorPS
{{
    [DllImport("user32.dll")]
    static extern bool SetCursorPos(int x, int y);
    
    [DllImport("user32.dll")]
    static extern bool GetCursorPos(out POINT lpPoint);
    
    [DllImport("user32.dll")]
    static extern void mouse_event(uint dwFlags, uint dx, uint dy, uint dwData, int dwExtraInfo);
    
    [StructLayout(LayoutKind.Sequential)]
    public struct POINT
    {{
        public int X;
        public int Y;
    }}
    
    const uint MOUSEEVENTF_MOVE = 0x0001;
    
    private static Thread jiggleThread;
    private static bool isRunning = false;
    private static bool zenMode = false;
    private static int intervalMs = 1000;
    
    public static void Start(bool virtualMode = false, int interval = 1000)
    {{
        if (isRunning) return;
        
        zenMode = virtualMode;
        intervalMs = interval;
        isRunning = true;
        
        jiggleThread = new Thread(JiggleLoop);
        jiggleThread.IsBackground = true;
        jiggleThread.Start();
    }}
    
    public static void Stop()
    {{
        isRunning = false;
        if (jiggleThread != null)
            jiggleThread.Join(100);
    }}
    
    public static bool IsRunning => isRunning;
    public static bool IsZenMode => zenMode;
    public static int Interval => intervalMs;
    
    private static void JiggleLoop()
    {{
        while (isRunning)
        {{
            try
            {{
                if (zenMode)
                {{
                    mouse_event(MOUSEEVENTF_MOVE, 1, 0, 0, 0);
                    Thread.Sleep(10);
                    mouse_event(MOUSEEVENTF_MOVE, 0xFFFFFFFF, 0, 0, 0);
                }}
                else
                {{
                    POINT point;
                    GetCursorPos(out point);
                    SetCursorPos(point.X + 1, point.Y);
                    Thread.Sleep(10);
                    SetCursorPos(point.X, point.Y);
                }}
            }}
            catch {{ }}
            
            Thread.Sleep(intervalMs);
        }}
    }}
}}
"@

function Start-MouseJiggle {{
    param([switch]$ZenMode, [int]$Interval = 1000)
    [MouseSimulatorPS]::Start($ZenMode, $Interval)
}}

function Stop-MouseJiggle {{
    [MouseSimulatorPS]::Stop()
}}

function Get-MouseJiggleStatus {{
    return [PSCustomObject]@{{
        Running = [MouseSimulatorPS]::IsRunning
        ZenMode = [MouseSimulatorPS]::IsZenMode
        Interval = [MouseSimulatorPS]::Interval
    }}
}}
'''

def generate_csharp(output_file: str):
    """Generate C# mouse simulator code."""
    with open(output_file, 'w') as f:
        f.write(CSHARP_TEMPLATE)
    print(f"✓ Generated C# code: {output_file}")

def generate_powershell(output_file: str):
    """Generate PowerShell mouse simulator code."""
    with open(output_file, 'w') as f:
        f.write(POWERSHELL_TEMPLATE)
    print(f"✓ Generated PowerShell code: {output_file}")

def main():
    parser = argparse.ArgumentParser(description='Generate mouse simulation code')
    parser.add_argument('--language', required=True, choices=['csharp', 'powershell'])
    parser.add_argument('--mode', default='both', choices=['physical', 'virtual', 'both'])
    parser.add_argument('--output', required=True, help='Output file path')
    args = parser.parse_args()
    
    if args.language == 'csharp':
        generate_csharp(args.output)
    else:
        generate_powershell(args.output)
    
    print(f"\nMode support: {args.mode}")
    print("  - Physical: Cursor actually moves on screen")
    print("  - Virtual (Zen): System thinks mouse moved, cursor stays still")

if __name__ == '__main__':
    main()